### ISSUE TITLE
WLC doesn't have option to chose screen display mode

### ISSUE THREAD

**Issue by chetanpm** [Cloudef/wlc#103]
Trying to set the resolution of my screen.
In the sway config file, on changing : "output res 1280x1024 pos 1280,0"  The displayed text and window gets smaller like it should when higher resolution is selected but the screen still stays in 1024x768 85hz.

**Comment by Cloudef** [comment]
This is because wlc does not provide modesetting API, and only currently provides API for changing OpenGL resolution, which is different thing. Access to modesetting is needed to affect monitor resolution.

**Comment by Cloudef** [comment]
Closing as duplicate of https://github.com/Cloudef/wlc/issues/37
