### ISSUE TITLE
wayland-protocols repo is down

### ISSUE THREAD

**Issue by maxlorenz** [Cloudef/wlc#115]
https://anongit.freedesktop.org/wayland/wayland-protocols/ not reachable for 2 days in a row now, building wlc fails

**Comment by Earnestly** [comment]
The correct HTTP URL is http://anongit.freedesktop.org/git/wayland/wayland-protocols.git

However wlc uses the GIT protocol which still works just fine here: git://anongit.freedesktop.org/wayland/wayland-protocols

**Comment by maxlorenz** [comment]
My bad, hat git configured to always use https (443)
