### ISSUE TITLE
wlc fails to build when `wayland-protocols` dep is not in `protos/` but installed system-wide

### ISSUE THREAD

**Issue by Fale** [Cloudef/wlc#119]
Could this be changed?

Use case: distro packaging.

**Comment by Earnestly** [comment]
I think it was decided that packing `wayland-protocols` is not appropriate for distributions as it's really only viable as something part of the source tree where compatibility can be maintained.

**Comment by Fale** [comment]
This would be against Fedora packaging policy (and also [Fedora has already packaged it](https://apps.fedoraproject.org/packages/wayland-protocols))

**Comment by Earnestly** [comment]
It's not a library so it can't possibly count as bundling

**Comment by SirCmpwn** [comment]
I agree with @Earnestly. This isn't a library in the traditional sense.

**Comment by Cloudef** [comment]
It would be possible to make it use systemwide install if it exists. But like Earnestly says, this just makes things more complicated. If system-wide _unstable_ protocol gets updated (xdg-shell for example), but wlc doesn't implement the changes, wlc will be broken.

**Comment by Cloudef** [comment]
I'll add alternative to build with systemwide wayland-protocols. Simply because @github doesn't bundle submodules in tarballs / zips.

**Comment by Fale** [comment]
thanks :) that would be awesome :)
