### ISSUE TITLE
Failing to build on Fedora

### ISSUE THREAD

**Issue by Fale** [Cloudef/wlc#121]
Hi,
In the process of trying to make wlc compiling in Fedora packaging system, I'm facing a problem during the compilation of tests.

What I do:

    # I get the git repo with submodules in a very hackish way to trick the building system. I'm not going to put here the commands to do so, but the result is the whole git repo of wlc and its submodules
    %cmake -DCMAKE_BUILD_TYPE=Upstream .
    make -j4

It fails (see build.txt and root.txt)

I've tried to change the make command so it's now:

    # I get the git repo with submodules in a very hackish way to trick the building system. I'm not going to put here the commands to do so, but the result is the whole git repo of wlc and its submodules
    %cmake -DCMAKE_BUILD_TYPE=Upstream .
    make

It fails differently (see build2.txt and root2.txt)

I'm wondering if this it's something I've done wrong or if the [guide](https://github.com/Cloudef/wlc#building) has something off

**Comment by Fale** [comment]
Sorry, attching the files
[build.txt](https://github.com/Cloudef/wlc/files/129615/build.txt)
[build2.txt](https://github.com/Cloudef/wlc/files/129618/build2.txt)
[root.txt](https://github.com/Cloudef/wlc/files/129616/root.txt)
[root2.txt](https://github.com/Cloudef/wlc/files/129617/root2.txt)

**Comment by Cloudef** [comment]
https://github.com/Cloudef/wlc/issues/69 See this issue. There is problem with your linker.

**Comment by Cloudef** [comment]
Curious, can you try appending -fuse-linker-plugin to the CFLAGS, -DCMAKE_C_FLAGS="-fuse-linker-plugin" and see if that works.

**Comment by Fale** [comment]
Thanks.

With `-DCMAKE_C_FLAGS="-fuse-linker-plugin"` it fails pretty badly (at cmake can not find any library that is installed on the OS)

With `cmake -DCMAKE_INSTALL_PREFIX=/usr/ -DCMAKE_BUILD_TYPE=Release ..` it does complain only about chck

**Comment by Cloudef** [comment]
You need to compile chck with Release or Debug too.
