### ISSUE TITLE
Mouse moves up when given input no matter what

### ISSUE THREAD

**Issue by Timidger** [Cloudef/wlc#126]
When running a window manager that utilizes WLC (either the example or any of the ones in development) by itself (i.e: not as a embedded window in an X environment), the mouse does not behave correctly. 

This is best seen with a touchpad. If you press your finger onto the touchpad without moving it then the mouse should stay in place (as it does on X). However with wayland+wlc it begins to move slowly upward on its own erratic accord. 

It was also discussed briefly on a [sway issue](https://github.com/SirCmpwn/sway/issues/491#issuecomment-187188421)

**Comment by Cloudef** [comment]
Sound like libinput issue, needs someone with touchpad to investigate anyways.

**Comment by N-006** [comment]
Its OK in weston, and its OK in sway only with libinput =< 1.1.5.

**Comment by Timidger** [comment]
@N-006 Thanks for the link and the info

**Comment by Cloudef** [comment]
@N-006 Thank you for checking it.

**Comment by Timidger** [comment]
Closed, as it's a libinput issue
