### ISSUE TITLE
Wrong view size when using wlc_view_get_geometry

### ISSUE THREAD

**Issue by ammen99** [Cloudef/wlc#128]
When I'm using wlc_view_get_geometry, I get wrong size for the view if it is a native wayland client, while   the function works well with Xwayland apps. After a bit of experimenting I found out that this can be easily solved if I modify wlc_view_get_geometry to use wlc_view_get_bounds() internally. Is this the intended behaviour, and how should this bug be fixed?

**Comment by Cloudef** [comment]
This is intended as wlc_view_get_bounds() isn't real geometry the client sees. There should be new function for getting visible geometry.

**Comment by ammen99** [comment]
If you want, take a look at this branch(the last commit implements the function,) tell me if it's ok and then I'll make a pull request. Link: https://github.com/ammen99/wlc/tree/visible_geometry

**Comment by Cloudef** [comment]
Yeah that looks ok, just fix the styling to be consistent. I would changes commets accordingly, for wlc_view_get_geometry in parenthesis (what client sees) and for wlc_view_get_visible_geometry (what wlc displays)
