### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by 1ace** [Cloudef/wlc#140]
Compilation is currently failing with a number of `undefined reference` to various symbols.
It looks like some library is missing from the compiler invocation, or symbols are not being exported.

[Full log of the compilation](https://gist.github.com/fa71164046c579fdfc9d) (using the Arch package)

**Comment by SirCmpwn** [comment]
Cannot reproduce. Looking at this build log I'm pretty sure your toolchain is FUBAR

**Comment by Earnestly** [comment]
This is GCC 6.0, hmm

**Comment by 1ace** [comment]
Yeah, I'm using [`gcc-git`](https://aur.archlinux.org/packages/gcc-git/) :]

I'm not entirely sure I follow though: is it just a different default behavior in the latest version of `gcc`?
Should `-fPIC` be added to the `CMakeLists.txt`?

**Comment by Earnestly** [comment]
Perhaps you shouldn't be using gcc-git if you're not pretty actively following its development :S

**Comment by SirCmpwn** [comment]
Using the git build of your toolchain and complaining to the maintainers of software you compile with it is fucking stupid.

**Comment by 1ace** [comment]
@SirCmpwn That was uncalled for.

I've been using it for a couple months now, and used its new warnings to find and fix a number of bugs in various projects. This is the first project that entirely breaks on the new version of `gcc`.
Besides, it's very likely this breakage will affect everyone once the new version is released, so it might as well get some light shed on it now, to give time to devs to fix it before everyone's build breaks.

**Comment by Earnestly** [comment]
Like I said, you're using LTO objects and likely need to use gcc's own `ar`, `ranlib` and so on.

**Comment by SirCmpwn** [comment]
If a new version of a compiler breaks a project that previously worked, it's obviously a bug with the compiler. Read the errors, the compiler is clearly fucked up. You're wasting our time.

**Comment by Earnestly** [comment]
GCC 6.0 does also introduce quite a few new nice warnings and can expose potential oversights with the code, although wlc itself has been run through various automatic API testers and seems to handle it far better than most common libraries, such as ncurses, which segfaults all over the place.

**Comment by Cloudef** [comment]
>/usr/bin/ranlib: compositor.c.o: plugin needed to handle lto object

This is same issue as https://github.com/Cloudef/wlc/issues/69

**Comment by 1ace** [comment]
Yup, same issue, same fix (`-DCMAKE_BUILD_TYPE=Release`). Closing this one, cheers!
