### ISSUE TITLE
Compositor crash on opening VTE terminal in xwayland

### ISSUE THREAD

**Issue by boomshroom** [Cloudef/wlc#148]
I have tested launching Liliterm from Orbement within i3 and sway from tty and have managed to crash both compositors when opening it, but only sometimes. Other times it seems to work fine.

[Orbement log](http://pastebin.com/BrKdQYSn)

[Sway log](http://pastebin.com/c63dgeaY)

I am using wlc 0.0.1, sway 0.3, and orbment commit r500.f0f67b3 on Arch Linux.

**Comment by Earnestly** [comment]
Probably related to https://github.com/Cloudef/wlc/issues/146 try rebuilding wlc

**Comment by Cloudef** [comment]
https://github.com/Cloudef/wlc/commit/b050e5acc1c6ddf97884d149eb1d370b31ccda2b Should fix this.

**Comment by boomshroom** [comment]
Updated to wlc-git-r913.2a9a7d0-1 and seems to be fixed.
