### ISSUE TITLE
wlc doesn't find dbus on Ubuntu systems due to multiarch

### ISSUE THREAD

**Issue by n3rdopolis** [Cloudef/wlc#15]
The current workaround is to run
ln -s /usr/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)/dbus-1.0/include/ /usr/lib/dbus-1.0/
and it finds dbus

I guess Ubuntu has the dbus-arch-deps.h file there

**Comment by Cloudef** [comment]
FindDbus.cmake has several flaws.
1. It should use pkg-config
2. Instead of hardcoding /usr/lib CMAKE_LIBRARY_PATH probably works better.

Will fix when I get home.

**Comment by Cloudef** [comment]
Can you try if latest commits fixed this.

**Comment by n3rdopolis** [comment]
It works! Thanks!
