### ISSUE TITLE
random key sym captured in bool (*key)(wlc_handle view, uint32_t time, const struct wlc_modifiers*, uint32_t key, enum wlc_key_state);

### ISSUE THREAD

**Issue by xeechou** [Cloudef/wlc#153]
Hi,

I am writing code to test key press event, and I found if I only pressed modifiers, I would get random key symbol,
the code is here:

    bool
    keyboard_key(wlc_handle view, uint32_t time, const struct wlc_modifiers *modifiers, uint32_t key, enum wlc_key_state state)
    {
	(void)time, (void)key;

	const uint32_t sym = wlc_keyboard_get_keysym_for_key(key, NULL);

	if (state == WLC_KEY_STATE_PRESSED) {
		//debug
		fprintf(glog_file, "KEYKEY: modifiers: %d, leds:%d,  key: %c\n", modifiers->mods, modifiers->leds, sym);
		struct wlc_modifiers test_modifiers;
		uint32_t test_key;
		uint64_t code;
		code = keysym_encode(modifiers, sym);
		keysym_decode(&test_modifiers, &test_key, code);
		if (test_modifiers.leds != modifiers->leds ||
		    test_modifiers.mods != modifiers->mods ||
		    test_key != sym) {
			fprintf(glog_file, "KEYKEY: encode\\decode is buggy\n");
		}
		//debug

In the log file, I found the last `key` field in `fprintf` is random key if no key is pressed. Is it normal?

**Comment by Cloudef** [comment]
You are printing uint32_t as %c. I'm not sure what you mean by "random key", but the keysym isn't ASCII character.

**Comment by xeechou** [comment]
I used `%c` for 'pretty print', I used `%d` before, the result is similar, the values of `sym` was not consistent while I didn't press any key(but modifiers). that is, meaning of "random key" means I got random value for `sym`.

**Comment by Earnestly** [comment]
What exactly is inconsistent here?  We know `%c` isn't going to work at all on `uint32_t` so you'll get random memory differencing that as a `char`.

But the number, the `%d` looks fine to me?

**Comment by xeechou** [comment]
No, the %d won't work either, I used %c just to see if `[a-z]` are mapped correctly, the inconsistent means if I don't press any key sym but modifiers for two times, the `sym` values are different.

**Comment by Cloudef** [comment]
No ctrl and alt are different keys, of course they will have different symbol.

**Comment by Earnestly** [comment]
Isn't there a function to print a nice character that's associated with the `uint32_t` value?

**Comment by xeechou** [comment]
I see, I thought keysym is independent from modifiers,
thanks.

**Comment by Cloudef** [comment]
@Earnestly xkb_keysym_get_name and xkb_keysym_to_utf8/xkb_keysym_to_utf32, depending what you want.
