### ISSUE TITLE
Bug in example in readme!

### ISSUE THREAD

**Issue by yohanesu75** [Cloudef/wlc#154]
Been chasing a bug like crazy for hours but finally found the issue.. 

Problem:
Client isn't rendered (with x11 backend).

Solution:
Need to add
```wlc_view_set_mask(view, wlc_output_get_mask(wlc_view_get_output(view)));```
to view_created callback (as in the more complex example.c).

**Comment by Cloudef** [comment]
Thanks, I'll add it.
