### ISSUE TITLE
wlc failes due to EGL error on older Intel, even with EGL_SOFTWARE=1

### ISSUE THREAD

**Issue by n3rdopolis** [Cloudef/wlc#16]
Hi.

It seems that running in DRM mode, results in an error due to an unsupported shader

I get
wlc error: extension 'GL_OES_EGL_image_external' unsupported in fragment shader

It works in x11 mode

Thanks

**Comment by Cloudef** [comment]
Does d58ac27 fix this for you?

**Comment by n3rdopolis** [comment]
It works. I had to check out master for the wlc submodule in orbment, but now it runs. Thanks!
