### ISSUE TITLE
cmake: missing CMakeLists.txt in lib/chck

### ISSUE THREAD

**Issue by mchalupa** [Cloudef/wlc#165]
Hi, tried to configure fresh clone of wlc and got this error:

```
CMake Error at CMake/subproject.cmake:39 (add_subdirectory):
  The source directory

    /home/marek/src/wlc/lib/chck

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  lib/CMakeLists.txt:5 (add_subproject)
```

**Comment by mchalupa** [comment]
Oh, yeah, I forgot to update submodules, my bad. Sorry for filing this issue.
But maybe that could be checked by cmake and an error message about submodules raised?

**Comment by Cloudef** [comment]
I think the error there already has enough clues to figure out. The submodule updated is after all documented in readme. Closing.
