### ISSUE TITLE
Error in the calculation of pointer movment for Logitech G500

### ISSUE THREAD

**Issue by psgarsenal** [Cloudef/wlc#166]
WHen using my main mouse on sway (which is using wlc), my cursor moves to the top left corner everytime I slightly move the mouse.
Here's a video, since it will be faster to see the problem than understand what I'm saying:
https://www.youtube.com/watch?v=Km1DwKZfC-c&feature=youtu.be

(from the video description)
First you see my Logitech G500 moving, then a random generic mouse.
Bus 003 Device 003: ID 046d:c068 Logitech, Inc. G500 Laser Mouse
Bus 001 Device 006: ID 062a:4101 Creative Labs Wireless Keyboard/Mouse

**Comment by Cloudef** [comment]
Er.., is this issue caused by particular mouse or use of 2 mouses? I don't really get the video.

**Comment by psgarsenal** [comment]
This is only caused by the logitech mouse, I plugged the second one just to check if it was only the logitech one, and it is

**Comment by Cloudef** [comment]
This is most likely libinput issue then.

**Comment by psgarsenal** [comment]
ok, will create a new issue at libinput repo, thanks!

**Comment by Cloudef** [comment]
Feel free reference to this issue, you could also test in weston to confirm this assumption.

**Comment by psgarsenal** [comment]
https://lists.freedesktop.org/archives/wayland-devel/2014-November/018011.html
It was already issued, seems like I was too dumb to google it, but looks like this patch has not been merged since november 2014. Anyway, keep up the good work!

**Comment by Cloudef** [comment]
Thanks, the issue can be left open for reference until fixed upstream.

**Comment by minus7** [comment]
I'm experiencing a similar issue using a Logitech Performance MX. If I move my mouse slowly right or down the pointer just won't move. Left/up works fine.

**Comment by psgarsenal** [comment]
https://wayland.freedesktop.org/libinput/doc/latest/motion_normalization.html

Just found this by random browsing, can you check the last section has any impact on our problem @minus7 ? I don't have my high-dpi mouse with me at the time so I cannot test it.

**Comment by minus7** [comment]
I tried changing the hwdb entry for my mouse to 1200DPI@125Hz (DPI configured using solaar before), `udevadm hwdb --update`ing and `udevadm control --reload`ing without success. Didn't try with rebooting however.

**Comment by thejan2009** [comment]
@minus7 I had the same issue with some Logitech mouse in sway. Completely fixed it with the following config
```
input "1133:49733:Logitech_Gaming_Mous" {
	accel_profile flat
	pointer_accel 0
}
```

**Comment by minus7** [comment]
Ah, you're right, I had that but I had the wrong name. To find the correct name you can just start sway with the debug flag `-d` and grep the output for `Found input device` – looking at the `libinput-list-devices` output does not give the correct name. `pointer_accel 0` isn't even necessary, `accel_profile flat` is the important part.

**Comment by SirCmpwn** [comment]
swaymsg -t get_inputs

**Comment by psgarsenal** [comment]
Some update: the issue does not appear for me when disabling acceleration in sway (`input "1133:49256:Logitec" accel_profile flat`). Closing this since a similar issue is opened and my problem is fixed.
