### ISSUE TITLE
xterm text corruption

### ISSUE THREAD

**Issue by tuncer** [Cloudef/wlc#170]
With wlc 0.0.3 as found in Archlinux, xterm under both orbment and sway randomly draws some characters partially. No such issue when running the same xterm under Weston.

**Comment by Earnestly** [comment]
Can you demonstrate this in a screenshot, or at least how to reproduce this visual(?) corruption?

**Comment by tuncer** [comment]
Start a vanilla (no Xresources) or custom (personal Xresources) uxterm and run `ls` to print some text. If none of the characters are incomplete, either run `ls` a few more times or start and exit `mc`. The way it looks is that the right half or upper right part of some of characters is invisible. Given that the vanilla uxterm exhibits the same issue, it's safe to assume it's unrelated to font config.

**Comment by Earnestly** [comment]
First of all, never use `uxterm`, use `-u8` instead as `uxterm` screws with your locale settings.

As for `xterm -u8` with no X resources file, I can reproduce this.  It's by default using the fixed font.

Screenshot:
![xterm corruption](https://ptpb.pw/1ICj.png)

**Comment by tuncer** [comment]
I didn't know about uxterm's locale bug. I'll change my bindings. Isn't there an X resource I can configure to achieve `-u8` by default (zero args passed to xterm)?

**Comment by tuncer** [comment]
What terminal do others run under Wayland? weston-terminal doesn't really work for me and st's Wayland fork is also very buggy in addition to st's general incompatibilities (compared to xterm).

**Comment by Earnestly** [comment]
According to xterm(1) you can set the class `utf8` to `2` to always use UTF-8 encoding regardless of locale while disallowing it from being disabled.  Other options are `0` (false), `1` (true) and `3` which is the default and based on the `locale` class.

**Comment by tuncer** [comment]
I have that already set to `1`, that seems sufficient then. Thanks for the tip.

**Comment by FreeFull** [comment]
It seems that whole columns of pixels are missing. Is there a mismatch between how wide xterm thinks it is, and how wide wlc considers it to be?

**Comment by FreeFull** [comment]
I think I've found another program that experiences the same rendering problem: The help system for SWI Prolog

**Comment by tuncer** [comment]
Does this still happen? I don't think I've seen this in xterm for a while now. I mean, maybe it's my config or it was actually fixed like the Firefox drop-down menu repaint bug has been.
