### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by colltoaction** [Cloudef/wlc#172]
Hi,

I've been using sway for a couple of weeks but I'm missing touch support, so I posted an issue here: https://github.com/SirCmpwn/sway/issues/721. They say this is probably something that can be implemented in WLC.

I have a Lenovo Yoga 3 14'', which has a touchscreen. It seems to be supported with different X desktops like LXDE, Unity, i3, but not on sway. It can scroll and sometimes pinch and zoom, but the focused element is usually wrong. I can't tap on any button because of this focus issue.

I just installed Weston, and it seems like touch works pretty well on weston-terminal, but I opened pcmanfm and I couldn't even hit the close button (pretty much what happens on sway). However, a weston-terminal window in sway doesn't work well.

I'd be happy to help testing a development version including changes for touch support.

Thanks,
Martín.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/wlc/pull/143 @Hummer12007 has open touch related code.

I don't have touchscreen myself, but extracting from your comment. Touch screen seems to work partially in wlc? (Same as in weston?). Pcmanfm sounds like x11 client and it may be they don't respond to touch events but only mouse events. Technically wlc could send both mouse and touch events though.

**Comment by tinchou** [comment]
Installed packages that may be related: `xf86-input-evdev`, `xf86-input-libinput`, `libinput`

In Weston, I can use some apps with pretty decent touch support. So far:
* the desktop itself: open a terminal by touching the icon and moving windows around by dragging the title bar
* weston-terminal: lets me select text (but not scroll)
* pcmanfm: lets me tap. lets me scroll, but sometimes it tries to select files. doesn't let me open folders by double tapping. it crashes pretty often.

In Sway, it feels like the touchscreen is being emulated as a mouse, but the behavior is not very consistent: 
* I can sometimes scroll (in Google Chrome) with one finger, sometimes with two
* I can sometimes pinch and zoom (in Google Chrome) with two fingers, sometimes with three
* I don't have any touch response from pcmanfm
* The focus seems to be where the cursor is, and not where the touch happens
* Touching a window doesn't focus it
* Tapping doesn't do anything (no click, nothing), even if the cursor is over a link or button

Also, I hit `pkill weston` in a terminal and I can see the following message in the terminal after the desktop goes away: `deactivating sessionut device '/dev/input/event5' .agged as input devicehpadudev as: Touchpad Touchscreen`.

**Comment by zog34** [comment]
Information pertaining to touch/gesture support in Plasma 5.10 (on Wayland): https://blog.martin-graesslin.com/blog/2017/04/how-input-works-touch-screen-edge-swipe-gestures/ and https://blog.martin-graesslin.com/blog/2016/12/how-input-works-pointer-input/
