### ISSUE TITLE
Support for color temperature

### ISSUE THREAD

**Issue by psgarsenal** [Cloudef/wlc#174]
Hi, one of the only things lacking for me is the support for things like f.lux or redshift.
As said here: jonls/redshift#55 the support has to be implemented at your level (as I understand it, I might be wrong).
Do you think this is possible?
Thanks for reading!

**Comment by Cloudef** [comment]
It was something I planned way back. There is @giucam who did protocol and modified redshift to use it. So as long as this protocol <https://github.com/giucam/orbital/blob/gamma/protocol/gamma-control.xml> is implemented in compositor it would work.

**Comment by giucam** [comment]
Note however that since the protocol is currently only in orbital i didn't try to upstream the redshift changes. So they are available on https://github.com/giucam/redshift

**Comment by psgarsenal** [comment]
Ok then going to check on sway side to see if ti is possible, thanks for the answers!

**Comment by Cloudef** [comment]
@psgarsenal It might make more sense to have this protocol inside wlc though, so sway gets it for free.

**Comment by psgarsenal** [comment]
I guess we could ask @SirCmpwn on his thoughts about this

**Comment by SirCmpwn** [comment]
Should go in wlc.

**Comment by embik** [comment]
This issue should be re-opened, right? It seems to be the "correct" issue for color temperature / redshift functionality. I'd really like to see this in wlc (and therefore in sway).

**Comment by craftyguy** [comment]
Any update on this?
