### ISSUE TITLE
CMSG_LEN(0) not accepted on FreeBSD

### ISSUE THREAD

**Issue by yohanesu75** [Cloudef/wlc#178]
Hi

I'm porting wlc to FreeBSD and am currently struggling with
https://github.com/Cloudef/wlc/blob/master/src/session/fd.c#L104

As the title says, FreeBSD doesn't seem to accept zero length messages.
Is there any simple way to work around this without rewriting too much of the code?

**Comment by Cloudef** [comment]
You could write some dummy data perhaps?

**Comment by yohanesu75** [comment]
I will try to send the payload (buffer) using send() when fd < 0.

**Comment by yohanesu75** [comment]
I will make a PR once cleaned up and finished..

**Comment by yohanesu75** [comment]
Fixed by settings controllen=0 and checking that on the receiving end.
