### ISSUE TITLE
Error messages spamming other TTYs

### ISSUE THREAD

**Issue by ldmldmldm** [Cloudef/wlc#183]
Hi.

Starting sway in one TTY then switching to another results in the following error messages being printed on the console (i believe these are from wlc). They appear about every half a second and thus make the other TTYs unusable.

```
[ 2124.905378 ] ERROR @wl_dev_intvar_get : error (-1)
[ 2124.905379 ] ERROR @wl_cfg80211_get_tx_power : error (-1)
[ 2124.905390 ] ERROR @wl_dev_intvar_get : error (-1)
[ 2124.905391 ] ERROR @wl_cfg80211_get_tx_power : error (-1)
...
```

Maybe it's appropriate to keep these on the TTY that the wm was launched from?

--
Thanks

**Comment by Earnestly** [comment]
These appear to be related to wireless, cfg80211 being a standard and the errors talking about transmission power.  `wl` is AFAIK a broadcom driver.

**Comment by Cloudef** [comment]
Those messages come from kernel. Not 100% sure but I would guess the driver is incomplete and those ops aren't implemented in the driver.

**Comment by ldmldmldm** [comment]
My bad, I thought they were from wlc.

Though if I start X11 and then switch to a free TTY they do not appear, yet if I start sway then switch to a free TTY they do appear ...
