### ISSUE TITLE
qt5 apps SIGABRT the WM when ran natively

### ISSUE THREAD

**Issue by Teteros** [Cloudef/wlc#185]
On wlc-git (https://github.com/Cloudef/wlc/commit/3f2c7206041992d272b3da2f946f2ff64b2862ca) qt5 programs tend to SIGABRT my sway session when ran through the wayland backend.

Not sure what the cause might be. It seems to be happening mainly when opening the context menus , although some programs (like mumble) crash the wm directly on their startup.

QT5 programs I tried which cause the WM to exit on my end:

Mumble (qt5 1.3.0) (on start)
qutebrowser (when right-clicking/copying?)
QT Creator (opening the menu bar and closing it)

**To reproduce:** Install any of the above and open them with the `QT_QPA_PLATFORM=wayland-efl` or `--platform wayland` env variable/parameter.

You need the `qt5-wayland` package as well.

[sway.log.txt](https://github.com/Cloudef/wlc/files/417515/sway.log.txt)
[gdb coredump](http://www10.zippyshare.com/v/QMt3kLhJ/file.html)

I wonder if it's a mesa/driver problem. Unrelated to this issueI, I have this slight mouse lag whenever I move the mouse between active windows, and it's gone when no windows are active.

Weston works fine though, including the qt5 apps listed above.

**Comment by Cloudef** [comment]
>wlc_view_get_bounds: Assertion `surface->size.w > 0 && surface->size.h > 0' failed.
Seems to be the problem.

**Comment by Teteros** [comment]
I'm not sure what fixed it, but since I started using wayland/wlc again this no longer occurs.
