### ISSUE TITLE
Confusing cmake message when xcb libs are not found

### ISSUE THREAD

**Issue by raboof** [Cloudef/wlc#19]
Suppose I don't have libxcb-composite0-dev installed, I get:

```
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find XCB (missing: XCB_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindXCB.cmake:23 (find_package_handle_standard_args)
  src/CMakeLists.txt:68 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/aengelen/dev/wlc/CMakeFiles/CMakeOutput.log".
```

Changing XCB_LIBRARIES to ${XCB_LIBRARIES} in CMake/FindXCB.cmake gives a more enlightening error, but my cmake skills are too limited to determine whether that makes any sense :)

**Comment by Cloudef** [comment]
I can see why replacing variable with string works here, the documentation for the function however only talks about variables. I agree that the messages aren't that great, however the variable name here is actually useful, when you want to manually control it. You can see what got assigned to the variable from CMakeCache.txt, or cmake-gui (most likely under "advanced" variables).

Some downstream Find*.cmake files seems to print out manually the variables during find, however I'd rather not do this.
