### ISSUE TITLE
Accepting requested geometry causes X windows to grow

### ISSUE THREAD

**Issue by kozec** [Cloudef/wlc#191]
Hello,

I found strange issue with wlc_set_view_request_geometry_cb callback.

As per documentation, I'm trying to agree on requested geometry by setting it using wlc_view_set_geometry. But doing so apparently sets size of X window larger by 2px in both directions, which in turn causes new size to be requested, ending in infinite loop of window slowly growing.

[Here is minimal example](http://pastebin.com/7gYUKA4x). Compiling it with ``` gcc test.c -lwlc -o test ```, running generated binary and then launching `DISPLAY=:1 xterm` from another console replicates this problem.

**Comment by Earnestly** [comment]
(Completely aside, consider using another pastebin, like ptpb.pw, as pastebin.com injects CRLF line endings.  (And everything else bad with it))

**Comment by kozec** [comment]
@Earnestly [Here you are](https://ptpb.pw/hb9F)

**Comment by kozec** [comment]
Just small followup, this is apparently caused by wlc ignoring border with in XCB_CONFIGURE_REQUEST.

There is slight chance I'll be able to get PR with fix together myself.

```
XCB_CONFIGURE_REQUEST (4194338) [484x316+0,0] bord 1
view_request_geometry --> 486x318
```

**Comment by Earnestly** [comment]
I wonder if this 2px thing is related to creating a gap where a border can be rendered?

**Comment by Cloudef** [comment]
Those gaps IIRC can be turned off by wm.

**Comment by kozec** [comment]
I'm sorry, I removed one comment here, as I was on completely wrong track there. Even window that doesn't send any size request gets same treatment and grows forever.

**Comment by kozec** [comment]
> Those gaps IIRC can be turned off by wm.

Do you happen to remember how?

```
[tom@silver wlc-git]$ grep -R gap
Binary file .git/objects/pack/pack-d3977f8f8e12e28e2ae9aa2894bc7bcf946b7ae7.pack matches
```

**Comment by Cloudef** [comment]
You need to call xcb_configure_window on the window with  XCB_CONFIG_WINDOW_BORDER_WIDTH bit included in the type.

**Comment by kozec** [comment]
@Cloudef 

Thanks, I managed to fix problem like this:

https://github.com/kozec/wlc/commit/fec9e46b0db30bd471c8e73c7ef7dea377ecb42a

Should I make PR? Is  there a chance that it will break something I don't know about?

**Comment by Cloudef** [comment]
Yes make a PR, It should not break anything as far I see.
