### ISSUE TITLE
wayland-protocols xdg-shell v6 needs to be implemented

### ISSUE THREAD

**Issue by gutsoo** [Cloudef/wlc#200]
GTK 3.22 uses the v6 of xdg shell, and GTK applications fail to load on compositors using wlc!

**Comment by alive4ever** [comment]
[xdg shell v6](https://lists.freedesktop.org/archives/wayland-devel/2016-August/030606.html) introduces backward incompatible behavior. #199 may be related to this issue.

**Comment by alive4ever** [comment]
After [last commit](https://github.com/Cloudef/wlc/commit/f4ff049cc30242eec9f33af7129d2e2a2865fb5a), sway is able to launch gnome-terminal inside wayland compositor, but crashes immediately when using mouse to interact with gnome-terminal menu.

**Comment by Cloudef** [comment]
Probably needs positioner or more popup crap, which I don't plan to implement yet.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/wlc/issues/210
