### ISSUE TITLE
Can't run sway from kmscon

### ISSUE THREAD

**Issue by DebugReport** [Cloudef/wlc#206]
https://github.com/SirCmpwn/sway/issues/969
OS: ArchLinux
Sway: version 0.10-rc1-67-gde79fee (2016-11-15, branch "master")
WLC: Version : r992.f8bb91b-1
Kmscon: Version : 8-3
Log: https://gist.github.com/DebugReport/59967439df06c6a1565c91202ec147b8

**Comment by Earnestly** [comment]
Yeah sure that won't work.  It's for the same reason X won't start from kmscon too.

See: https://github.com/dvdhrm/kmscon/issues/65 and https://github.com/dvdhrm/kmscon/issues/103

**Comment by DebugReport** [comment]
Now only waiting for fixed in kmscon?

**Comment by Earnestly** [comment]
Honestly I doubt you'll ever see support for this in kmscon, dvdhrm has made it pretty clear that the only way forward is using DMs to start different sessions, be they wayland compositors, kmscon or xorg.
