### ISSUE TITLE
Plugable renderer

### ISSUE THREAD

**Issue by kozec** [Cloudef/wlc#228]
Hello,

this is more question than bug so far. I've noticed that there is [theoretical support for having multiple renderers](https://github.com/Cloudef/wlc/blob/1910a6ddffe53b8886c48566dce0ad6fd7f60f76/src/platform/render/render.c#L142) implemented and `wlc-render.h` is part of include/ dir. Is there any way for API user to implement such renderer and force wlc to use it?

**Comment by SirCmpwn** [comment]
Not presently.

**Comment by kozec** [comment]
Thanks for answer.
