### ISSUE TITLE
wlc error when starting sway inside tmux

### ISSUE THREAD

**Issue by andmarti1424** [Cloudef/wlc#229]
I am currently using wlc throw sway, but I get the following error while trying to start it inside tmux:

[wlc] could not activate vt1

is there a way to do this?
thanks!

**Comment by oblitum** [comment]
I'm just trying out sway for the first time and hit the same issue.

**Comment by SirCmpwn** [comment]
No, you can't start it from tmux.

**Comment by oblitum** [comment]
And it started fine from outside tmux.

**Comment by oblitum** [comment]
No support planned? There's simply no way?

**Comment by SirCmpwn** [comment]
Not unless you intend to debug it yourself and send a patch, no.
