### ISSUE TITLE
fbdev backend

### ISSUE THREAD

**Issue by ollieparanoid** [Cloudef/wlc#230]
I would like to see a `fbdev` backend in `wlc` and I will try to implement it, when I find time.

@Cloudef: Is there anything I should look out for?

**Comment by Earnestly** [comment]
Isn't fbdev being actively discourged (such as no longer adding new drivers) by the linux kernel devs in favour of kms?

**Comment by ollieparanoid** [comment]
Thanks for the hint, you are absolutely right. I thought `fbdev` was still state of the art, as a backend for `weston` has been written. Now I need to reconsider if I really need `fbdev` for my use-case.
