### ISSUE TITLE
SDL/OpenGL applications crash on startup with SIGILL in XWayland

### ISSUE THREAD

**Issue by simon-v** [Cloudef/wlc#24]
The crash occurs immediately after an SDL surface is created. The backtrace is usually empty. The same applications work in Weston.

Linux 4.0.6-1-Arch
wlc r387
orbment r385

Are there any details i can provide to help identify the source of the problem?

**Comment by Earnestly** [comment]
Hm, I can't seem to replicate this with a basic SDL2 program or another which
loads textures in the form of images (SDL2/SDL_image).  Which SDL2 program
fails under orbment for you?

**Comment by simon-v** [comment]
Actually, it doesn't seem limited to just SDL. It manifested in Zdoom, OpenRA and Shovel Knight at first, then proceeded to trigger in SLADE (the map editor component) and Gimp. I can't really see the connection between all those. I suspected that, perhaps, it's because they require specific window sizes and are non-resizable, but i can't really back it up.

**Comment by simon-v** [comment]
Closing because i can no longer reproduce this issue after rebuilding the library and compositor today. Much thanks!
