### ISSUE TITLE
Build has too many warnings

### ISSUE THREAD

**Issue by Enerccio** [Cloudef/wlc#258]
Low priority issue, but if you are building a lot, it is pretty crappy. 

Most of it is inside chck submodule, but some are inside wlc itself, like in xdg_cb_popup_grab by @kozec

**Comment by Earnestly** [comment]
They're pretty much all non null warnings because the compiler isn't smart enough, making the warning mechanism chck added fairly pointless.  It's all rather unfortunate.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/wlc/commit/32dfed15b74f28e77bc4170ef72f22c3542e71be should fix them
