### ISSUE TITLE
Touch event reports view by mouse position

### ISSUE THREAD

**Issue by kozec** [Cloudef/wlc#266]
Hello,

I'm playing with touch events and I've noticed pretty weird behavior - view reported by touch events is not view that user is touching, but view that mouse pointer is above.

Is this intentional?

**Comment by SirCmpwn** [comment]
The mouse pointer should probably be moved in response to touch events.

**Comment by kozec** [comment]
> The mouse pointer should probably be moved in response to touch events.

Yes, but even doing that is not enough, as first touch event always fires before pointer is moved and this reports wrong view.

**Comment by SirCmpwn** [comment]
Sure, it sounds like a bug to me.

**Comment by kozec** [comment]
By the way, another problem where I'm not 100% sure if it's a bug...

[Code in touch.c](https://github.com/Cloudef/wlc/blob/c263cc3d064ba78da9c8728722432717ed9385c0/src/compositor/seat/touch.c#L78) appears to send touch events with coordinates in screen space, but I'm pretty sure that Wayland client expects them in surface space. Tapping on gnome calculator suggest the same, as button that is actually pressed when I touch its window is offseted and offset depends on window position.

**Comment by SirCmpwn** [comment]
Definitely sounds like a bug to me.
