### ISSUE TITLE
drm not working...

### ISSUE THREAD

**Issue by yohanesu** [Cloudef/wlc#27]
drm is not listed in wl_registry outputs.

**Comment by yohanesu** [comment]
When launching my compositor based on wlc with "EGL_LOG_LEVEL=debug" I can see that DRI2 loads /usr/lib/xorg/modules/dri/i965_dri.so (wonder why not 915 which is the loaded kernel module..) 
When launching the client I can see it loads swrast_dri.so.. So for the compositor hardware rendering works but not the clients...

**Comment by yohanesu** [comment]
At launch of the compositor I get a warning "Failed to bind socket: ". Can this be related?

**Comment by Cloudef** [comment]
Lets continue on #28
