### ISSUE TITLE
[FreeBSD] Lose all input when tty switch back to sway

### ISSUE THREAD

**Issue by johalun** [Cloudef/wlc#283]
As the title says. Probably won't be fixed because of a wlc replacement for sway coming soon, just thought I'd add an issue to share my discovery.

**Comment by oblitum** [comment]
Try out sway for first time. I'm starting it out of tty, mouse works but input doesn't. Switch back and forth between tty and sway doesn't help.

@johalun do you have the reference about when sway will switch from wlc?

**Comment by SirCmpwn** [comment]
>mouse works but input doesn't.

wat

**Comment by oblitum** [comment]
I mean, up to now I could only see the mouse pointer moving, any other kind of input has no response, keyboard or mouse clicks.

**Comment by oblitum** [comment]
Also, I'm not on FreeBSD, I'm on a freshly installed ArchLinux.

**Comment by oblitum** [comment]
I had to check `/run/user/1000` for the sway socket and `export SWAYSOCK=/run/user/1000/sway-ipc.1000.515.sock`, otherwise `swaymsg` always returns "sway socket not detected". Now `swaymsg -t get_outputs` is returning my HDMI display information correctly, but `swaymsg -t get_inputs` just returns an empty result.

**Comment by oblitum** [comment]
Had to to that from another tty, since the first is taken by Sway/Wayland.

**Comment by oblitum** [comment]
Ops, really sorry for the noise. Got it working finally \o/. The sole issue was the the use of Mod4 in the default configuration file, it simply isn't working for me yet, changing it to Mod1 (Alt) for now solves it. Also, from termite inside sway `get_inputs`, etc is working normally.
