### ISSUE TITLE
Support for color space

### ISSUE THREAD

**Issue by pauledd** [Cloudef/wlc#285]
Hi there
I dont know if this is the right place or somehow related to https://github.com/Cloudef/wlc/issues/174
but are there plans to implement support for selecting color spaces?

What I mean is FULL RGB aka 0-255 and Limited RGB aka 16-235 known for TV video purposes as
described here: https://referencehometheater.com/2014/commentary/rgb-full-vs-limited/

I often have to switch between the two color ranges because if I do photo editing I need the whole color range and when I watch tv I need to use reduced color range. Thats the only reason that keeps me from using wayland/sway (beside of setting Refresh rate and specific gamma values ).

**Comment by cafehaine** [comment]
sway is now working to switch to wlroots, so if you want to use this on sway you should create an issue there
[https://github.com/swaywm/wlroots](wlroots)

**Comment by pauledd** [comment]
ok, thanks.
