### ISSUE TITLE
Control what key gets sent to the client

### ISSUE THREAD

**Issue by SirCmpwn** [Cloudef/wlc#30]
I'm not sure if it's possible for wlc to handle this, but I'd like to give my users the ability to remap keys (i.e. switch caps lock and escape). Can keyboard.key be called with pointers to the key info instead of values?

**Comment by Earnestly** [comment]
The manual for orbment details how you can do this via xkbcommon as it's exposed there: https://github.com/Cloudef/orbment/blob/master/orbment.1.in#L92

**Comment by SirCmpwn** [comment]
Thanks, I guess that'll do.
