### ISSUE TITLE
Keys held down when the last x window closes continue to be held down when the next one opens

### ISSUE THREAD

**Issue by SirCmpwn** [Cloudef/wlc#31]
1. Open urxvt
2. Close it with ctrl+d
3. Open urxvt again, it immediately closes because ctrl+d continues to be held down so far as it can tell

Alternatively:

1. Open urxvt (or any x terminal)
2. Close it with ctrl+d
3. Open chromium/firefox/etc and see that it prompts you to save a bookmark (ctrl+d shortcut)

**Comment by Earnestly** [comment]
Maybe related https://github.com/Cloudef/orbment/issues/93

*[If you're using orbment, perhaps submit to orbment's issue tracker?]*

**Comment by SirCmpwn** [comment]
Not using orbment, but thanks for the link.

**Comment by Cloudef** [comment]
c8e73ea

**Comment by SirCmpwn** [comment]
Thanks!
