### ISSUE TITLE
WLC_BIT_OVERRIDE_REDIRECT is not set when running dmenu

### ISSUE THREAD

**Issue by SirCmpwn** [Cloudef/wlc#34]
For some reason wlc_view_get_type comes back as `0`.

**Comment by Cloudef** [comment]
Should be fixed in 986927f

**Comment by SirCmpwn** [comment]
Thank you.

**Comment by SirCmpwn** [comment]
Related problem. When I do not have an x window open, and I run dmenu (from within [sway](https://github.com/SirCmpwn/sway), I can't type anything into dmenu. It works if I have an x window open to begin with, though. I give unmanaged windows (like dmenu) focus when they appear, but it doesn't seem to help.
