### ISSUE TITLE
Use floating point instead of int for dragging windows

### ISSUE THREAD

**Issue by Philipp-M** [Cloudef/wlc#4]
Hey there, nice project.
Looks quite nice already(loliwm)
I was just playing around a little bit with it, and found an issue while moving a window. If moving the cursor slowly while dragging a window, it wont move(I think because delta values under 0 are cut to 0), also after moving a window a lot, the cursor seems to go other ways than the window, it kinda drifts away. My experience says, that it is a float to int typecast issue(had some similar issues playing with touch and android).

**Comment by Cloudef** [comment]
Good point. I already fixed similar issue with subpixel mouse movement.
I should do the same here as well.
