### ISSUE TITLE
Handle surface scale parameter

### ISSUE THREAD

**Issue by Cloudef** [Cloudef/wlc#57]
Needed for hidpi clients and scaling non hidpi clients.

**Comment by Cloudef** [comment]
Note that surface scale is integral, this is for very good reasons which you can read on wayland mailing lists. Non-integral scaling can be still done by setting output resolution with wlc_output_set_resolution.

**Comment by JonathanReeve** [comment]
:+1: for this all the way. This is what's preventing me, and everyone else with a modern display, from using SirCmpwn/sway.

**Comment by SirCmpwn** [comment]
@JonathanReeve it helps as a workaround to set your display's resolution to half of the actual resolution in your sway config. That's what I do for my macbook.

**Comment by harrisonrodgers** [comment]
Hi. Could the [scale](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_output-event-scale) parameter of [wl_output](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_output) be what we want? 
> A scale larger than 1 means that the compositor will automatically scale surface buffers by this amount when rendering. This is used for very high resolution displays where applications rendering at the native resolution would be too small to be legible.

**Comment by SirCmpwn** [comment]
That's partially related, but not the whole picture.

**Comment by harrisonrodgers** [comment]
Ok. Adding `scale=2` into an `[output]` section of the Weston config seems to scale everything as expected for a HiDPI monitor. Maybe we can look at the Weston code to see how exactly they do it.

**Comment by Cloudef** [comment]
In order to do this, you need both scale parameter in wl_output and scale parameter in wl_surface. If surface scale == output scale, you don't need to do anything, the client is already rendering in native resolution. If surface scale > output scale, you need to downscale the surface. If surface scale < output scale, you need to scale the surface up.

The scaling should be done during render phase in gles2.c, it won't affect anything else but visual output. The visible bounds probably need to be multiplied / divided accordingly.

**Comment by enckse** [comment]
If/when hidpi is available I'd be more than willing to try it (sway + wlc) via Arch and/or AUR.

Mildly unrelated my use case for hidpi is a dell 7370 where I would like to get my 2 external monitors + laptop screen all working (in sway) - I know configuration for multiple monitors may not _entirely_ fall on wlc but if there are good resources for that and someone could point me to the docs that would be fantastic (again since I'll have 1 hidpi display and 2 non-hidpi displays)

**Comment by Cloudef** [comment]
I would need access to such display, or at least someone willing to spare their time at IRC to write this feature myself.

**Comment by enckse** [comment]
I can't do much for getting you a display of your own but I can be in IRC to assist in some capacity - very much willing to do bleeding edge stuff, I have all of X working so it's not like I'm relying on the wlc stack for my day-to-day operations (yet, but that's what I'd like)

**Comment by Cloudef** [comment]
Apparently @SirCmpwn offered as black box tester for me as well. I won't probably be doing much this month though.

**Comment by enckse** [comment]
Understood - whenever you get there, if I can be of _any_ assistance let me know!

**Comment by tinchou** [comment]
Can I help? I started using Sway a week ago or so. I have a 14' FullHD display, and I'd love to see things a little bigger, without the blur of the output res hack that people suggest in the sway repo (add `output eDP-1 res 1280x720` or similar to the config file)

**Comment by ss1h2a3tw** [comment]
Regarding to the non integral scaling,
according to https://bugs.freedesktop.org/show_bug.cgi?id=93315#c20
Maybe we could set a real output scale and a fake output scale for clients?

**Comment by dobegor** [comment]
Any progress on this? Using 12.5' FHD display stops me from moving to wayland/sway.

**Comment by ss1h2a3tw** [comment]
I have been pretty busy till today, there's still issue on xwayland scale  handling , I 'll try to fix it in few days.

**Comment by tinchou** [comment]
Let me know if you want me to try out any changes! I have a 13'' FHD

**Comment by dobegor** [comment]
I am able to beta-test before it's pushed too.
Just ping me here (intel skylake video, 12.5' FHD) if needed.

**Comment by Dinduks** [comment]
We have 4k 28" screens and FHD 15" laptops at work. I can beta-test too!

**Comment by dobegor** [comment]
@Cloudef sorry, why did you close this issue?

**Comment by tinchou** [comment]
See #173. Does this mean we can now scale without the windows blurring??

**Comment by ss1h2a3tw** [comment]
@tinchou  blurring will still happen when the client don't support surface scale bigger than 1 ex. weston-terminal
and X11's app ex. vlc
