### ISSUE TITLE
wl_cb_shell_surface_set_popup not implemented

### ISSUE THREAD

**Issue by danhosler** [Cloudef/wlc#60]
qt apps will crash with this error "wl_shell_surface@22: error 1: wl_cb_shell_surface_set_popup @ line 107 is not implemented" whenever menus are involved (clicking menu bar or right clicking screen). Pretty much anything that involves popup menus seems to trigger this error. I am running wlc with xwayland disabled to create this error.

**Comment by Cloudef** [comment]
I've made these stubs not send error to client. However not yet implemented indeed.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/orbment/issues/118
