### ISSUE TITLE
-fstack-protector-strong requires gcc 4.9

### ISSUE THREAD

**Issue by danhosler** [Cloudef/wlc#62]
gcc 4.8 does not support -fstack-protector-strong. upgrade to gcc 4.9 is required.

**Comment by Cloudef** [comment]
http://www.cmake.org/cmake/help/v3.3/module/CheckCCompilerFlag.html Should use this and provide ability to disable upstream flags with cmake variable.

**Comment by Cloudef** [comment]
http://cloudef.pw/armpit/cmake-flags.txt Including related discussion from #cmake channel.

**Comment by Cloudef** [comment]
Should be fixed in commit https://github.com/Cloudef/wlc/commit/dc44e27b94456d544251cbe496dcb682f05596c0 please recheck
