### ISSUE TITLE
Provide hooks for overriding default behavior

### ISSUE THREAD

**Issue by Cloudef** [Cloudef/wlc#7]
Most useful drawing for example view borders, background, or any other custom behavior where it makes sense.

**Comment by SirCmpwn** [comment]
:+1: 

Would particularly like to override borders. I would say that the things you mentioned (border, background) are both probably the domain of the consumer of this library, and don't really belong in the library itself.

**Comment by Cloudef** [comment]
Background most likely moves to be a wayland client. Drawing borders, focus or other view related things and effects though makes sense inside compositor. Wlc will not provide facilities for drawing itself, you must choose library yourself for that.

**Comment by SirCmpwn** [comment]
That seems fine. I'm just looking for a way to get rid of the default borders and close/max/min buttons and so on. The background as a wayland client makes sense, too.

**Comment by Cloudef** [comment]
For those, you can't get rid of those until somebody stands up with a protocol extension for that. Client draws borders, and currently there is no way to communicate between compositor/client to not do that.

**Comment by SirCmpwn** [comment]
Oh, so those aren't wlc's domain?

**Comment by Cloudef** [comment]
Nope, wlc borders would be the server-side borders. The thing Weston does for Xwayland clients. Weston test applications and GTK draw client side borders.

**Comment by SirCmpwn** [comment]
I see. Thanks for clarifying.
