### ISSUE TITLE
manipulating mouse-position

### ISSUE THREAD

**Issue by tobiaslieber** [Cloudef/wlc#71]
Hi,

As far as I can see, there is no feature to manipulate the mouse position. This would be nice to have for a virtual desktop size (for example, as it has been implemented in waimea).
I just browsed the sourcecode and in general it is possible to implement this with WLC. But it will certainly change the API of WLC, depending on the implementation massively.

Is such a feature wanted, or are there objections against such a feature?

**Comment by Cloudef** [comment]
There is no objection for such feature as long as it's useful. I don't see how it would cause massive API change. As this should be possible with function that takes in a output + coordinates.

**Comment by tobiaslieber** [comment]
Yes, that is one possible way of doing it.
However, I think, if it would be implemented in this way, then one probably runs into the "flaw" that the cursor probably will "jump" after every motion event. This made me wonder, if it may be smarter to implement a method in wlc-interface that can manipulate the wlc_pointer_origin pos in the method input_event, basically before it is set by wlc_pointer_motion.
But I guess you are way more familiar with the internals of WLC and which option leads to the best design.

**Comment by Cloudef** [comment]
>"flaw" that the cursor probably will be made "jumping" after every motion event.
I don't consider this as a flaw. If mouse is moved then mouse is moved. What are you trying to do?

**Comment by tobiaslieber** [comment]
For me this "easy" implementation would be fine. I am aiming for virtual desktop-size of several full-sized output-resolutions.
So, if the mouse is at the right border of the screen, say (x,y) I want it to jump to the position (1,y). (To make this meaningful, there is also some moving of windows needed). (This feature is closest to the oversized desktop of https://en.wikipedia.org/wiki/Virtual_desktop)

**Comment by Cloudef** [comment]
Unless you want to animate the windows, you can also set their view mask to different of your output so they are effectively hidden. All sorts of animations as of now though don't fit well in wlc, so I would not think those (unless you want to contribute code for that too :))

Wlc by no means is not in ABI stability phase yet. Not at least until the most common problems of desktop are solved and the #47 is done. So you don't have to stress yourself by introducing API that might not work well for some use cases. (And even then if something is horribly broken I would rather break API than introduce tech debt, as with posix_open for example)

So I think the simple approach that works for you is the best to take here.
I assume you already have implementation going on for your virtual desktop, just do the code that works for you (following the CONTRIBUTING.rst please) and we'll look at that then :)
