### ISSUE TITLE
wlc fails to configure when `chck` dep is not in `lib/` but installed system-wide

### ISSUE THREAD

**Issue by zetok** [Cloudef/wlc#73]
Could this be changed?

Use case: distro packaging.

**Comment by Cloudef** [comment]
Linking against external chck is not possible due to this issue https://github.com/Cloudef/chck/issues/20

Even then I suggest still linking against the submodule chck statically since that library is very low-level and will have lots of ABI changes.

**Comment by jannisch** [comment]
I also want to create a distro package so it would be nice to have lib/chck in future release versions.

**Comment by Earnestly** [comment]
Don't package chck, it's not intended as a package.

**Comment by jannisch** [comment]
No I don't want to use chck as shared library or create an isolated chck package.
But when I want to package wlc-0.0.1 I have to fetch the latest chck source and copy it to lib/, don't I? It isn't a package for this specific release then.

**Comment by Earnestly** [comment]
Ah yes, this issue with github not including submodules in release tarballs, sigh.  This is a known problem.

**Comment by jannisch** [comment]
Thanks, I see.
From my point of view the simplest solution would be tagging a chck release. It could be fetched and copied into the wlc/lib/ directory then before compiling.

**Comment by Cloudef** [comment]
Well, chck doesn't really do releases. It's just utility code, I think github is being retarted here. More reasons to move away.. Better solution would be just include the chck files we use in the same repo :/

**Comment by jannisch** [comment]
It's quite a lot of work I guess. Or what do you think about adding a bundled version with chck as a "binary asset" to the release?

**Comment by Earnestly** [comment]
It doesn't solve any of the problems, you might as well just download the latest commit of chck.

**Comment by jannisch** [comment]
Just an idea to make it a bit more packaging-friendly. But I already got a working one, please feel free to close the conversation.
