### ISSUE TITLE
Provide animation API

### ISSUE THREAD

**Issue by Cloudef** [Cloudef/wlc#8]
Easings, timings, conflict handling and such coupled with custom drawing. Of course we want wobbly windows and desktop cubes. Having this API in wlc allows render loop to be efficient as possible.

**Comment by Cloudef** [comment]
We may also consider if wlc should become bit more lower level (leave drawing to wm?) or expose more internals to not have all this crud.

**Comment by ammen99** [comment]
I'm particularly interested in this feature. It would be great if wlc could just handle views' textures to the compositor and leave it to draw them as it sees fit.

**Comment by ammen99** [comment]
@Cloudef  I wondered whether it should be possible to use the output pre(or post) render hooks to draw custom GL stuff? I mean, is the context bound during these phases? I tried drawing something, but nothing shows up - is it my fault or such feature is just not supported?

**Comment by Cloudef** [comment]
@ammen99 It's possible, not offically supported though, as it relies on implementation details, however if we can guarantee some GL context state during pre/post render hooks, it could be officially supported. Animations also are sort of possible by using the timer sources.

**Comment by Cloudef** [comment]
As for nothing showing up, you need to take into account the coordinate system provided by the active shader. It's probably better idea to use your own shader when draing in the hooks.

**Comment by ammen99** [comment]
After some experimenting I noticed the following: There is no problem using the GL context from the compositor side. However, to achieve that, we must change the function set_program() in gles2.c - we must use glGetIntegerv(GL_CURRENT_PROGRAM) to check if we glUseProgram,
because context->program cannot be updated if the compositor uses another(non-WLC) program and then the renderer won't change the program back to the standard, resulting in nothing visible and a lot of GL errors. If you think this is a good solution, I'll send another pull request to fix that.

Another proposition:
To resolve the issue with animations, we may provide API for one of the following:
1) Get textures of a surface(should be easy), most flexible choice and leave the rendering to compositor
2) Render a surface with transform(for ex. GL matrix) - also not easy
3) Render a surface with custom program - almost the same as 1)

What do you think about these options? If there is a viable solution, I'll implement it, because I need such functionality for my compositor.

**Comment by Cloudef** [comment]
>we must use glGetIntegerv(GL_CURRENT_PROGRAM) to check if we glUseProgram,
Could we just not make wlc call glUseProgram each time it draws something. It's probably bit overhead, but much less than glGet* functions that cause synchronization (e.g. driver stall). Anyhow, would make sure correct program is always used when wlc draws.

>1) Get textures of a surface(should be easy), most flexible choice and leave the rendering to compositor

Currently wlc-render.h only contains renderer independant functions, such as wlc_write_pixels, wlc_read_pixels and wlc_surface_render.

Texture id's are rendered dependant, so we might need some way to get enum of which renderer is in use. (Theoritically it's even possible outputs could run different renderers)

Note that when receiving texture ids, you should not store them and only receive / use them in render hook. As they may die / change as they please, and they won't work from output to another (they are separate context).

>Render a surface with transform(for ex. GL matrix) - also not hard
This would be own shader.

>Render a surface with custom program - almost the same as 1), but would require backend-specific API
What would be the API? I don't see why this would need one, assuming program == shader.

**Comment by ammen99** [comment]
I didn't mean providing all of these functions, maybe just the first option, something like wlc_surface_get_textures() and wlc_output_get_renderer(), which should allow the compositor to do just everything it wants(animations and etc.) Then the compositor could just disable the default drawing(by setting output mask to 0) and render everything and also send fake pointer events(pointer events are also controlled through the visibility mask) to support input redirection(in compositor's side). Do you approve of such API? I can do it after I fix the subsurfaces issues.

**Comment by Cloudef** [comment]
It feels like you are bypassing so many things in wlc, that make wlc sort of pointless. (Handling input, view state and stack for you). It would make more sense to have way to get texture, and tell wlc to not render views, either by some api function or returning for example false in render hooks. If this is not enough, and you have non traditional window manager for need to even override input, I would say wlc is going to be more burdersome than useful. (As you pretty much duplicate most of that wlc tries to do for you).

Maybe it's better to ask what is that you are trying to accomplish on higher level?

**Comment by ammen99** [comment]
I want to make something which in X11 world is called compositing window manager. And wlc is not that useless in my case - when no effects, it just does it's job. When I want to render a desktop cube for example, I disable wlc drawing and input and render everything by myself, then switch back to wlc. In this case wlc saves me the implementation of the whole wayland protocol, shell, xwayland integration and others, which is(at least for me) great.

**Comment by Cloudef** [comment]
I see, you just want bypass the input during effect. That should be fair enough.

**Comment by ammen99** [comment]
So should I start working on it? Will you accept it in WLC?

**Comment by Cloudef** [comment]
Do it and lets see what you end up with. I'm all for supporting this in wlc. Lets just try make it so that it has least amount of API overhead as possible.

**Comment by ammen99** [comment]
I have the following question: Why is the behaviour of wlc_output_schedule_render() different when I use a nested compositor(X11 backend) and standalone compositor(on tty)? I use it to make some sort of animation(updated on each pre-render hook). When using in nested compositor, animation is smooth. When on tty, it is sometimes(maybe half of the time) laggy. Is there something I don't understand which might cause this?

**Comment by Cloudef** [comment]
Render scheduling behaviour is not different between backends. What's is different is that on drm you wait for page flip and finish frame once page has been flipped. On X11 the finish is called immediately after rendering.

**Comment by ammen99** [comment]
So there isn't a way to "force" drm flipping? Sorry, I have almost no knowledge of drm.

**Comment by Cloudef** [comment]
That's not surprising the linux graphic stack is very badly documented. The best I can show you is this example https://github.com/dvdhrm/docs/blob/master/drm-howto/modeset-double-buffered.c There is nothing to "force", you simply have to wait that the buffer was flipped on the GPU before you can push more stuff to it.

**Comment by ammen99** [comment]
Thank you. Anyway, I solved the problem by improving performance of rendering(with glBlitFramebuffer). It seems that if animation rendering is fast enough, output repaints can be done on every drm page flip with just wlc_output_schedule_repaint().

**Comment by Cloudef** [comment]
The GALLIUM_HUD env variable is useful for gathering statics on rendering performance when running compositor. WLC_DEBUG=render-loop can be used to see render loop activity and timing values.
