### ISSUE TITLE
Error compiling vertex

### ISSUE THREAD

**Issue by yohanesu** [Cloudef/wlc#80]
Hi

I just updated my system (Arch Linux 64bit) and suddenly wlc fails for me.

wlc: (ERROR) Compiling vertex: 0:4(14): error: initializer of global variable `ortho' must be a constant expression

Will investigate further.

**Comment by sinapinto** [comment]
did you find a solution? i have the same issue

**Comment by Earnestly** [comment]
It was fixed in https://github.com/Cloudef/wlc/pull/78

**Comment by sinapinto** [comment]
ah, thanks
