### ISSUE TITLE
Xwayland views get visually corrupted from time to time

### ISSUE THREAD

**Issue by SirCmpwn** [Cloudef/wlc#90]
Firefox, for example, will occasionally have a single tab that's FUBAR with graphical corruption all over the place. The only solution is to restart the client. I also see this sort of problem with urxvt occasionally.

**Comment by Cloudef** [comment]
Not sure if this is wlc or Xwayland problem. Glamor in Xwayland is at least known to cause text corruption in past.

**Comment by SirCmpwn** [comment]
I haven't seen this in ages. Closing.
