### ISSUE TITLE
FindWLC.cmake installed to wrong path

### ISSUE THREAD

**Issue by SirCmpwn** [Cloudef/wlc#91]
Which leads to it not working. It should be in `/usr/share/cmake-3.4/Modules/`, not `/usr/share/cmake/modules/`.

**Comment by Cloudef** [comment]
I guess the official cmake answer for this is: "Do not install the Find*.cmake files" They want developers to copy and maintain their own. No wonder all .cmake files are crap.

I guess I'll remove the install() from wlc.

**Comment by SirCmpwn** [comment]
Lame.

**Comment by jpumc** [comment]
couldn't you export the wlc target and use it in other projects.

**Comment by Cloudef** [comment]
That's already done if you use it as submodule. However when you want to find system install, cmake has no convention for system location for Find*.cmake files provided by upstream. Thus every person always copies the Find*.cmake files into their project, and it's reason why they all are crappy and buggy (even the files that come with CMake itself).

**Comment by jpumc** [comment]
Well I have lots of directories in $LIBDIR/cmake that contain files like somethingConfig.cmake which includes somethingTargets,cmake which contains imported targets. $LIBDIR/cmake is in find_package search path by default.

I think something like
```
$LIBDIR/cmake/
  wlc/
     wlcConfig.cmake           // generated from wlcConfig.cmake.in by configure_package_config_file()
     wlcTargets.cmake          // generated by install(EXPORT wlcTargets ...), contains the wlc imported target
     wlcTargets-Release.cmake  // also generated by install(EXPORT...)
```
would work. The target could then define the dependencies and include paths so you just `target_link_libraries(my_compositor wlc)` and it handles them for you.
