### ISSUE TITLE
Add xcb-util-image to arch linux dependencies

### ISSUE THREAD

**Issue by upwhere** [Cloudef/wlc#94]
Some clients (XWayland) require libxcb-image.so.
On arch linux, libxcb-image.so is provided by `xcb-util-image`.
`xcb-util-image` is not listed in the PKGBUILD

Log excerpt:
```
[12:33:07.525] wlc: Xwayland started (DISPLAY :0)
[12:33:07.525] (WARN) wlc: libxcb-image.so: cannot open shared object file: No such file or directory
[12:33:07.526] -- Orbment is ready --
```

Since not all programs require libxcb-image.so it could be added to optdepends.

**Comment by SirCmpwn** [comment]
Leave a comment on the AUR package. This isn't an upstream problem. The dependency is documented here: https://github.com/Cloudef/wlc#building

**Comment by Cloudef** [comment]
It seems to be in the AUR package anyways.
